# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{compass-grid-coordinates-plugin}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Stacoviak"]
  s.date = %q{2009-09-29}
  s.description = %q{Grid Coordinates is Simple. Grid Coordinates is just a grid. It also supports nested grids and is also able to generate the CSS for a multitude of grid coordinates.}
  s.email = %q{adam@gethandcrafted.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "compass-grid-coordinates-plugin.gemspec",
     "lib/grid-coordinates.rb",
     "lib/grid-coordinates.rb",
     "lib/grid-coordinates/compass_plugin.rb",
     "lib/grid-coordinates/compass_plugin.rb",
     "lib/grid-coordinates/sass_extensions.rb",
     "lib/grid-coordinates/sass_extensions.rb",
     "sass/grid-coordinates/grid.sass",
     "sass/grid-coordinates/grid.sass",
     "templates/project/_partials/_base.sass",
     "templates/project/_partials/_base.sass",
     "templates/project/_partials/_grid.sass",
     "templates/project/_partials/_grid.sass",
     "templates/project/manifest.rb",
     "templates/project/manifest.rb",
     "templates/project/styles.sass",
     "templates/project/styles.sass",
     "test/compass-grid-coordinates-plugin_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/handcrafted/compass-grid-coordinates-plugin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Grid Coordinates is a Compass plugin based on Tyler Tate's 1kb CSS Grid project}
  s.test_files = [
    "test/compass-grid-coordinates-plugin_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<compass>, [">= 0.8.16"])
      s.add_development_dependency(%q<echoe>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<compass>, [">= 0.8.16"])
      s.add_dependency(%q<echoe>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<compass>, [">= 0.8.16"])
    s.add_dependency(%q<echoe>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
