# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grid-coordinates}
  s.version = "1.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Stacoviak"]
  s.date = %q{2009-10-01}
  s.description = %q{Grid Coordinates is a Compass extension. It's simple. It's just a grid that supports nested grids and is also able to generate the CSS for a multitude of grid coordinates.}
  s.email = %q{adam@gethandcrafted.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "README.textile",
     "Rakefile",
     "VERSION",
     "lib/grid-coordinates.rb",
     "lib/grid-coordinates/compass_extension.rb",
     "lib/grid-coordinates/sass_extensions.rb",
     "sass/grid-coordinates/grid.sass",
     "templates/project/manifest.rb",
     "templates/project/partials/_base.sass",
     "templates/project/partials/_grid.sass",
     "templates/project/styles.sass"
  ]
  s.homepage = %q{http://github.com/handcrafted/grid-coordinates}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Grid Coordinates is a Compass extension based on Tyler Tate's 1kb CSS Grid project.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<compass>, [">= 0.8.16"])
    else
      s.add_dependency(%q<compass>, [">= 0.8.16"])
    end
  else
    s.add_dependency(%q<compass>, [">= 0.8.16"])
  end
end
